# Generated by Django 4.2.1 on 2023-05-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('znotes', '0004_remove_profile_link_profile_date_modified_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='user',
        ),
    ]
