# Generated by Django 4.2.1 on 2023-05-28 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('znotes', '0005_rename_name_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='name',
        ),
    ]
